version: '3.9'
services:
  test_api:
    container_name: fastapi_project-test
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: "pytest -vv"
    networks:
      - test_network
networks:
  test_network:
    name: test_network